/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.agentscope.core.credential;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;
import reactor.test.StepVerifier;

class CredentialBaseTest {

    private static final class StubCredential extends CredentialBase {
        StubCredential() {
            super(null);
        }

        @Override
        public Class<? extends io.agentscope.core.model.ChatModelBase> getChatModelClass() {
            throw new UnsupportedOperationException();
        }
    }

    @Test
    void idIsAutoGeneratedHexWhenAbsent() {
        StubCredential a = new StubCredential();
        StubCredential b = new StubCredential();
        assertNotNull(a.getId());
        assertEquals(32, a.getId().length());
        assertTrue(a.getId().matches("[0-9a-f]{32}"));
        assertNotEquals(a.getId(), b.getId());
    }

    @Test
    void listModelsDefaultThrowsUnsupported() {
        StubCredential c = new StubCredential();
        StepVerifier.create(c.listModels())
                .expectErrorSatisfies(e -> assertTrue(e instanceof UnsupportedOperationException))
                .verify();
    }

    @Test
    void getChatModelClassMustBeImplemented() {
        StubCredential c = new StubCredential();
        assertThrows(UnsupportedOperationException.class, c::getChatModelClass);
    }
}
