/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.agentscope.core.message;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Behaviour spec for {@link DataBlock} — the unified multimedia container that
 * replaces the legacy image/audio/video subclasses.
 */
class DataBlockTest {

    private final ObjectMapper mapper = new ObjectMapper();

    @Test
    @DisplayName("Builder constructs a DataBlock with URLSource")
    void testBuildWithUrlSource() {
        URLSource src = URLSource.builder().url("https://example.com/cat.png").build();
        DataBlock block = DataBlock.builder().source(src).name("cat.png").build();

        assertInstanceOf(URLSource.class, block.getSource());
        assertEquals("https://example.com/cat.png", ((URLSource) block.getSource()).getUrl());
        assertEquals("cat.png", block.getName());
        assertNotNull(block.getId());
        assertFalse(block.getId().isEmpty());
    }

    @Test
    @DisplayName("Builder constructs a DataBlock with Base64Source")
    void testBuildWithBase64Source() {
        Base64Source src =
                Base64Source.builder().mediaType("image/png").data("iVBORw0KGgo=").build();
        DataBlock block = DataBlock.builder().source(src).id("fixed-id").build();

        assertInstanceOf(Base64Source.class, block.getSource());
        assertEquals("image/png", ((Base64Source) block.getSource()).getMediaType());
        assertEquals("iVBORw0KGgo=", ((Base64Source) block.getSource()).getData());
        assertEquals("fixed-id", block.getId());
        assertNull(block.getName());
    }

    @Test
    @DisplayName("JSON round-trip preserves source/id/name and emits type=\"data\"")
    void testJsonRoundTrip() throws Exception {
        DataBlock original =
                DataBlock.builder()
                        .source(URLSource.builder().url("https://example.com/x.mp3").build())
                        .id("abc123")
                        .name("x.mp3")
                        .build();

        String json = mapper.writeValueAsString(original);
        assertTrue(json.contains("\"type\":\"data\""), "missing type discriminator: " + json);
        assertTrue(json.contains("\"id\":\"abc123\""));
        assertTrue(json.contains("\"name\":\"x.mp3\""));

        DataBlock parsed = mapper.readValue(json, DataBlock.class);
        assertEquals("abc123", parsed.getId());
        assertEquals("x.mp3", parsed.getName());
        assertInstanceOf(URLSource.class, parsed.getSource());
        assertEquals("https://example.com/x.mp3", ((URLSource) parsed.getSource()).getUrl());
    }

    @Test
    @DisplayName("ContentBlock polymorphic deserialization resolves type=\"data\" to DataBlock")
    void testJsonDeserializationViaContentBlock() throws Exception {
        String json =
                "{\"type\":\"data\","
                        + "\"source\":{\"type\":\"url\",\"url\":\"https://example.com/v.mp4\"},"
                        + "\"id\":\"vid-1\",\"name\":\"v.mp4\"}";
        ContentBlock block = mapper.readValue(json, ContentBlock.class);

        assertInstanceOf(DataBlock.class, block);
        DataBlock data = (DataBlock) block;
        assertEquals("vid-1", data.getId());
        assertEquals("v.mp4", data.getName());
    }

    @Test
    @DisplayName("id is auto-generated when omitted")
    void testIdAutoGenerated() {
        DataBlock a =
                DataBlock.builder()
                        .source(URLSource.builder().url("https://example.com/a").build())
                        .build();
        DataBlock b =
                DataBlock.builder()
                        .source(URLSource.builder().url("https://example.com/b").build())
                        .build();

        assertNotNull(a.getId());
        assertNotNull(b.getId());
        assertFalse(a.getId().isEmpty());
        assertFalse(b.getId().isEmpty());
        // Two independent blocks must not share an id.
        assertFalse(a.getId().equals(b.getId()), "auto-generated ids should be unique");
    }

    @Test
    @DisplayName("name is optional — null name is preserved and omitted from JSON")
    void testNameIsOptional() throws Exception {
        DataBlock block =
                DataBlock.builder()
                        .source(URLSource.builder().url("https://example.com/x.png").build())
                        .build();

        assertNull(block.getName());
        String json = mapper.writeValueAsString(block);
        // @JsonInclude(NON_NULL) on the class should suppress null name from output.
        assertFalse(json.contains("\"name\""), "expected no name field in JSON, got: " + json);
    }

    @Test
    @DisplayName("Null source is rejected at construction time")
    void testNullSourceRejected() {
        assertThrows(NullPointerException.class, () -> DataBlock.builder().name("x").build());
    }
}
