/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.agentscope.harness.agent.example;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyList;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import io.agentscope.core.agent.RuntimeContext;
import io.agentscope.core.message.Msg;
import io.agentscope.core.message.MsgRole;
import io.agentscope.core.message.TextBlock;
import io.agentscope.core.model.ChatResponse;
import io.agentscope.core.model.Model;
import io.agentscope.core.session.Session;
import io.agentscope.harness.agent.HarnessAgent;
import io.agentscope.harness.agent.IsolationScope;
import io.agentscope.harness.agent.filesystem.spec.RemoteFilesystemSpec;
import io.agentscope.harness.agent.store.InMemoryStore;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import reactor.core.publisher.Flux;

/**
 * Example: Distributed shared remote filesystem mode with different {@link IsolationScope} levels.
 *
 * <h2>Context</h2>
 * <p>In remote mode, selected paths (such as {@code MEMORY.md}, {@code memory/}) are routed to a
 * shared key-value store ({@link InMemoryStore} here; typically Redis or another distributed
 * store in production). The {@code IsolationScope} controls the store namespace prefix and
 * therefore which agent calls can read each other's stored data.
 *
 * <p>Three scopes are demonstrated:
 * <ul>
 *   <li>{@link IsolationScope#SESSION} – each session gets its own namespace. Calls within the
 *       same session see the same data; calls from a different session see an empty namespace.</li>
 *   <li>{@link IsolationScope#USER} – all sessions of the same user share one namespace. A
 *       different user gets an isolated namespace.</li>
 *   <li>{@link IsolationScope#AGENT} – all users and sessions share one namespace per agent.
 *       Data written by any caller is visible to all other callers of the same agent.</li>
 * </ul>
 *
 * <p>Assertions directly inspect the {@link InMemoryStore} using the namespace keys generated by
 * the scopes:
 * <ul>
 *   <li>{@code SESSION}: {@code agents/<agentId>/sessions/<sessionId>/root/MEMORY.md}</li>
 *   <li>{@code USER}:    {@code agents/<agentId>/users/<userId>/root/MEMORY.md}</li>
 *   <li>{@code AGENT}:   {@code agents/<agentId>/shared/root/MEMORY.md}</li>
 * </ul>
 *
 * <p>This test does not call {@link HarnessAgent#call} for all cases — it uses
 * {@link io.agentscope.harness.agent.workspace.WorkspaceManager#writeUtf8WorkspaceRelative}
 * directly where possible to keep the example focused on namespace routing rather than agent
 * conversation mechanics.
 */
class RemoteFilesystemIsolationScopeExampleTest {

    @TempDir Path workspace;

    // -------------------------------------------------------------------------
    // Scenario A: SESSION scope
    // -------------------------------------------------------------------------

    /**
     * SESSION scope — writes from session-1 are NOT visible to session-2.
     *
     * <p>The store namespace is {@code agents/<agentId>/sessions/<sessionId>}, so each session
     * has a fully independent MEMORY.md.
     */
    @Test
    void sessionScope_differentSessions_isolatedNamespaces() throws Exception {
        Files.createDirectories(workspace);
        InMemoryStore store = new InMemoryStore();

        try (HarnessAgent agent =
                HarnessAgent.builder()
                        .name("assistant")
                        .model(stubModel("done"))
                        .workspace(workspace.toAbsolutePath().normalize().toString())
                        .filesystem(
                                new RemoteFilesystemSpec(store)
                                        .isolationScope(IsolationScope.SESSION))
                        .session(mock(Session.class))
                        .build()) {

            // Call as session-1 and write MEMORY.md
            agent.call(userMsg("from session-1"), ctx("session-1", "alice")).block();
            agent.getWorkspaceManager()
                    .writeUtf8WorkspaceRelative(
                            ctx("session-1", "alice"), "MEMORY.md", "session-1 notes");

            // Verify the data landed in the session-1 namespace
            assertNotNull(
                    store.get(
                            List.of("agents", "assistant", "sessions", "session-1", "root"),
                            "/MEMORY.md"),
                    "MEMORY.md should be stored under the session-1 namespace");

            // Verify session-2 namespace is empty (isolated)
            assertNull(
                    store.get(
                            List.of("agents", "assistant", "sessions", "session-2", "root"),
                            "/MEMORY.md"),
                    "session-2 namespace should be empty");
        }
    }

    /**
     * SESSION scope — writes from the same session are shared across calls.
     */
    @Test
    void sessionScope_sameSession_sharedNamespace() throws Exception {
        Files.createDirectories(workspace);
        InMemoryStore store = new InMemoryStore();

        try (HarnessAgent agent =
                HarnessAgent.builder()
                        .name("assistant")
                        .model(stubModel("done"))
                        .workspace(workspace.toAbsolutePath().normalize().toString())
                        .filesystem(
                                new RemoteFilesystemSpec(store)
                                        .isolationScope(IsolationScope.SESSION))
                        .session(mock(Session.class))
                        .build()) {

            // First call writes MEMORY.md under session-1
            agent.call(userMsg("call 1"), ctx("session-1", "alice")).block();
            agent.getWorkspaceManager()
                    .writeUtf8WorkspaceRelative(
                            ctx("session-1", "alice"), "MEMORY.md", "shared memory");

            // Second call with same session can read it
            agent.call(userMsg("call 2"), ctx("session-1", "alice")).block();

            assertNotNull(
                    store.get(
                            List.of("agents", "assistant", "sessions", "session-1", "root"),
                            "/MEMORY.md"),
                    "MEMORY.md should persist in the session-1 namespace across calls");
        }
    }

    // -------------------------------------------------------------------------
    // Scenario B: USER scope
    // -------------------------------------------------------------------------

    /**
     * USER scope — different sessions of the same user share a single namespace.
     *
     * <p>The namespace is {@code agents/<agentId>/users/<userId>}, so data written by session-A
     * is immediately visible to session-B of the same user.
     */
    @Test
    void userScope_sameUser_sharedAcrossSessions() throws Exception {
        Files.createDirectories(workspace);
        InMemoryStore store = new InMemoryStore();

        try (HarnessAgent agent =
                HarnessAgent.builder()
                        .name("assistant")
                        .model(stubModel("done"))
                        .workspace(workspace.toAbsolutePath().normalize().toString())
                        .filesystem(
                                new RemoteFilesystemSpec(store).isolationScope(IsolationScope.USER))
                        .session(mock(Session.class))
                        .build()) {

            // Call as alice / session-a and write MEMORY.md
            agent.call(userMsg("hi from session-a"), ctx("session-a", "alice")).block();
            agent.getWorkspaceManager()
                    .writeUtf8WorkspaceRelative(
                            ctx("session-a", "alice"), "MEMORY.md", "alice's memory");

            // The entry lands in the user-scoped namespace
            assertNotNull(
                    store.get(
                            List.of("agents", "assistant", "users", "alice", "root"), "/MEMORY.md"),
                    "MEMORY.md should be stored under alice's user namespace");

            // Call as alice / session-b — sees the same store namespace
            agent.call(userMsg("hi from session-b"), ctx("session-b", "alice")).block();
            assertNotNull(
                    store.get(
                            List.of("agents", "assistant", "users", "alice", "root"), "/MEMORY.md"),
                    "alice's MEMORY.md should still be accessible from session-b");
        }
    }

    /**
     * USER scope — different users have isolated namespaces.
     */
    @Test
    void userScope_differentUsers_isolatedNamespaces() throws Exception {
        Files.createDirectories(workspace);
        InMemoryStore store = new InMemoryStore();

        try (HarnessAgent agent =
                HarnessAgent.builder()
                        .name("assistant")
                        .model(stubModel("done"))
                        .workspace(workspace.toAbsolutePath().normalize().toString())
                        .filesystem(
                                new RemoteFilesystemSpec(store).isolationScope(IsolationScope.USER))
                        .session(mock(Session.class))
                        .build()) {

            agent.call(userMsg("alice writes"), ctx("s1", "alice")).block();
            agent.getWorkspaceManager()
                    .writeUtf8WorkspaceRelative(ctx("s1", "alice"), "MEMORY.md", "alice's data");

            // Bob's namespace should be empty
            assertNull(
                    store.get(List.of("agents", "assistant", "users", "bob", "root"), "/MEMORY.md"),
                    "bob's namespace should be isolated from alice's");
        }
    }

    // -------------------------------------------------------------------------
    // Scenario C: AGENT scope
    // -------------------------------------------------------------------------

    /**
     * AGENT scope — all users and sessions share one namespace per agent.
     *
     * <p>The namespace is {@code agents/<agentId>/shared}, so any user's write is visible
     * to any other user of the same agent.
     */
    @Test
    void agentScope_allCallersShareOneNamespace() throws Exception {
        Files.createDirectories(workspace);
        InMemoryStore store = new InMemoryStore();

        try (HarnessAgent agent =
                HarnessAgent.builder()
                        .name("shared-assistant")
                        .model(stubModel("done"))
                        .workspace(workspace.toAbsolutePath().normalize().toString())
                        .filesystem(
                                new RemoteFilesystemSpec(store)
                                        .isolationScope(IsolationScope.AGENT))
                        .session(mock(Session.class))
                        .build()) {

            // Alice writes
            agent.call(userMsg("alice"), ctx("s1", "alice")).block();
            agent.getWorkspaceManager()
                    .writeUtf8WorkspaceRelative(
                            ctx("s1", "alice"), "MEMORY.md", "shared knowledge");

            assertNotNull(
                    store.get(
                            List.of("agents", "shared-assistant", "shared", "root"), "/MEMORY.md"),
                    "MEMORY.md should be in the agent-scoped shared namespace");

            // Bob's call also reads from the same shared namespace
            agent.call(userMsg("bob"), ctx("s2", "bob")).block();
            assertNotNull(
                    store.get(
                            List.of("agents", "shared-assistant", "shared", "root"), "/MEMORY.md"),
                    "shared namespace should still contain the data after bob's call");
        }
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private static RuntimeContext ctx(String sessionId, String userId) {
        return RuntimeContext.builder().sessionId(sessionId).userId(userId).build();
    }

    private static Msg userMsg(String text) {
        return Msg.builder()
                .role(MsgRole.USER)
                .content(TextBlock.builder().text(text).build())
                .build();
    }

    private static Model stubModel(String text) {
        Model model = mock(Model.class);
        when(model.getModelName()).thenReturn("stub-model");
        ChatResponse chunk =
                new ChatResponse(
                        "stub-id",
                        List.of(TextBlock.builder().text(text).build()),
                        null,
                        Map.of(),
                        "stop");
        when(model.stream(anyList(), any(), any())).thenReturn(Flux.just(chunk));
        return model;
    }
}
